name: backend-deploy-production
on:
  workflow_dispatch:

jobs:
  deploy-backend:
    uses: ./.github/workflows/backend-deploy.yml
    with:
      cloud-env: production
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit
